import type { Metadata } from 'next'
import PackagingCaseStudy from '@/components/PackagingCaseStudy'
import { buildCaseStudySchema } from '@/lib/case-study-schema'

const title = 'Audio Enhancement Packaging System Case Study'
const description = 'How a daily-use equipment package was redesigned around product organization, quality consistency, and a more scalable production path.'
const image = '/images/work/audio-enhancement/teacher-box-blue-bg.jpg'
export const metadata: Metadata = { title, description, alternates: { canonical: '/work/audio-enhancement-packaging-system' }, openGraph: { title: `${title} | Logic Pac`, description, type: 'article', images: [image] } }
export default function Page() {
  const schema = buildCaseStudySchema({ slug: 'audio-enhancement-packaging-system', headline: title, description, image, client: 'Audio Enhancement' })
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema.article) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema.breadcrumb) }} /><PackagingCaseStudy study={{
    client:'Audio Enhancement', eyebrow:'Structural Packaging & QC', title:'When the package stays in use after delivery.', lede:'A structural packaging system for classroom audio equipment—designed to organize components, support daily use, and improve consistency as the manufacturing path evolved.', heroImage:image, heroAlt:'Audio Enhancement teacher box packaging on a blue background', meta:[['Client','Audio Enhancement'],['Category','Education technology'],['Focus','Structure and production quality']], overviewTitle:'The package was part of the product experience.', overview:['This was not disposable transit packaging. Teachers would continue using the package to organize and access classroom microphone equipment, making structure, finish, and durability visible long after delivery.','As product and volume needs evolved, the packaging also needed a production path capable of holding those standards consistently.'], constraints:[['Daily-use organization.','Components needed clear locations and easy access after installation.'],['Visible quality.','Finish and craftsmanship affected the perceived quality of the equipment itself.'],['Transit protection.','The interior had to retain multiple components through shipment and handoff.'],['Supplier readiness.','The manufacturing path needed to support repeatable output as requirements expanded.']], solutionTitle:'Engineer the package as a product hub', solutions:[['Purpose-built interior','The layout organizes the microphone system and accessories instead of treating them as loose shipment contents.'],['Durable structure','The outer format is designed for continued handling and storage beyond the first unboxing.'],['Quality checkpoints','Visible finishes, fit, and component placement become explicit acceptance criteria.'],['Production transition','Current product quality can be protected while a stronger long-term manufacturing path is qualified.']], outcomeTitle:'A packaging system aligned with how the product is actually used.', outcomes:['The redesigned direction treated packaging as part of the classroom experience, not a cost to discard after delivery. It also made structural and finish consistency central to production quality.','For beauty and wellness brands, the parallel is reusable presentation, device packaging, treatment systems, and premium kits that remain with the customer. In those formats, packaging durability and organization are part of product value.'], secondaryImage:'/images/work/audio-enhancement/updated-packaging-interior.jpg', secondaryAlt:'Interior of Audio Enhancement packaging with organized equipment compartments', evidence:'Audio Enhancement is approved for public reference. Shipping, landed-cost, and SKU-expansion metrics are withheld here pending case-study-specific approval.', relatedHref:'/capabilities', relatedLabel:'Explore Packaging Capabilities', projectType:'Structural Packaging'
  }} /></>
}
