export type BlogPost = {
  slug: string
  title: string
  description: string
  date: string
  author: string
  tag: string
  readTime: string
  image: string
  gradient: string
  published: boolean
}

export const blogPosts: BlogPost[] = [
  {
    slug: 'custom-packaging-cost-beauty-brands',
    title: 'How Much Does Custom Packaging Cost? A Real Pricing Breakdown for Beauty Brands',
    description: 'Actual per-unit ranges by format — folding cartons, rigid boxes, tubes, and specialty finishes. What drives the price up, how to compare quotes, and where brands overpay.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Pricing',
    readTime: '10 min read',
    image: '/images/portfolio/foil-stamped-cylinder.jpeg',
    gradient: 'linear-gradient(135deg,#1a1a2e,#16213e,#0f3460)',
    published: true,
  },
  {
    slug: 'sustainable-beauty-packaging-sb54',
    title: 'Sustainable Beauty Packaging: What Actually Works, What\'s Greenwashing, and What the Regulations Require',
    description: 'PCR performance reality, SB 54 deadlines, EU PPWR impact, FTC Green Guides compliance, and real cost comparisons between sustainable and conventional materials.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Sustainability',
    readTime: '12 min read',
    image: '/images/portfolio/velvet-interior-unboxing-kit.jpeg',
    gradient: 'linear-gradient(135deg,#0d2818,#1a4a2e,#2d6a4f)',
    published: true,
  },
  {
    slug: 'influencer-kit-packaging-design',
    title: 'How to Design an Influencer Kit That Actually Gets Posted (Not Thrown Away)',
    description: 'The 5 elements that separate kits that get filmed from kits that get recycled. Real cost ranges, production timelines, and how to brief your packaging partner.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Influencer Kits',
    readTime: '9 min read',
    image: '/images/portfolio/skincare-launch-pr-mailer.jpg',
    gradient: 'linear-gradient(135deg,#0f2027,#203a43,#2c5364)',
    published: true,
  },
  {
    slug: 'custom-packaging-timeline',
    title: 'How Long Does Custom Packaging Take? The Real Timeline from Concept to Shelf',
    description: 'The real production timeline: design, prototyping, tooling, manufacturing, and freight. What delays projects, what speeds them up, and how to work backward from your launch date.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Planning',
    readTime: '9 min read',
    image: '/images/portfolio/holiday-kits.jpeg',
    gradient: 'linear-gradient(135deg,#1a0a2e,#2e1a4a,#4a2c6a)',
    published: true,
  },
  {
    slug: 'sb54-packaging-compliance-beauty',
    title: 'SB 54 Packaging Compliance for Beauty Brands: Deadlines, Requirements, and What to Do Now',
    description: 'California\'s Packaging Reduction Act hits beauty brands harder than most. Primary, secondary, and tertiary packaging audit frameworks, timeline, and compliance roadmap.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Compliance',
    readTime: '11 min read',
    image: '/images/portfolio/cosmetics-folding-carton.jpeg',
    gradient: 'linear-gradient(135deg,#1a1a2e,#0f3460,#16213e)',
    published: true,
  },
  {
    slug: 'holiday-gift-set-packaging-beauty-brands',
    title: 'Holiday Gift Set Packaging for Beauty Brands: Formats, Timelines, and What to Plan Now',
    description: 'Holiday packaging decisions start in Q1 for Q4 delivery. Advent calendars, multi-SKU gift sets, and discovery kits — real timelines, formats, and cost ranges.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Holiday',
    readTime: '10 min read',
    image: '/images/portfolio/24-door-advent-calendar.jpeg',
    gradient: 'linear-gradient(135deg,#2e1a0a,#4a2c1a,#6a3c2a)',
    published: true,
  },
  {
    slug: 'glass-vs-plastic-beauty-packaging',
    title: 'Glass vs. Plastic Packaging for Beauty Brands: The Real Comparison',
    description: 'Glass, PET, HDPE, PCR, aluminum — compared on cost, weight, freight, breakage, sustainability, and shelf perception. The decision framework for beauty packaging materials.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Materials',
    readTime: '9 min read',
    image: '/images/portfolio/premium-beauty-gift-set1.jpg',
    gradient: 'linear-gradient(135deg,#0a2e1a,#1a4a3c,#2c6a5a)',
    published: true,
  },
  {
    slug: 'packaging-finishes-guide-foil-uv-emboss',
    title: 'Packaging Finishes Guide: Foil Stamping, Spot UV, Embossing, and Soft-Touch Explained',
    description: 'Every packaging finish explained with real cost-per-unit additions, what each does to perceived value, and when to use one vs. stack multiple.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Finishes',
    readTime: '11 min read',
    image: '/images/portfolio/soft-touch-spot-uv.jpg',
    gradient: 'linear-gradient(135deg,#1a0a2e,#3c1a5a,#5a2c7a)',
    published: true,
  },
  {
    slug: 'skincare-packaging-design-guide',
    title: 'Skincare Packaging Design: A Guide to Formats, Materials, and What Works at Shelf',
    description: 'Category-specific packaging guide for skincare brands. Primary packaging by product type, material selection, formula compatibility, clean beauty considerations, and cost planning.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Design',
    readTime: '11 min read',
    image: '/images/portfolio/holiday-epicutis-gift-sets.jpg',
    gradient: 'linear-gradient(135deg,#2e0a1a,#4a1a2e,#6a2c3c)',
    published: true,
  },
  {
    slug: 'packaging-brief-template-beauty-brands',
    title: 'How to Write a Packaging Brief: The Template That Gets You Better Quotes',
    description: 'The document that determines whether your packaging project runs smoothly or costs 2x in revisions. Section-by-section walkthrough of a complete packaging brief.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Planning',
    readTime: '9 min read',
    image: '/images/portfolio/shelf-ready-display-unit.jpeg',
    gradient: 'linear-gradient(135deg,#1a1a2e,#2e2e3e,#3c3c4e)',
    published: true,
  },
  {
    slug: 'how-to-choose-beauty-packaging-manufacturer',
    title: 'How to Choose a Beauty Packaging Manufacturer: The Decision Framework',
    description: 'What to look for, what to avoid, and the qualification questions that separate reliable packaging partners from unreliable ones. 4 partner models compared.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Strategy',
    readTime: '11 min read',
    image: '/images/portfolio/influencer-adidas-nemesis.jpg',
    gradient: 'linear-gradient(135deg,#0f2027,#1a3a43,#2c5a64)',
    published: true,
  },
  {
    slug: 'custom-cosmetic-packaging-formats',
    title: 'Custom Cosmetic Packaging Formats: Every Option Explained for Beauty Brands',
    description: 'Every cosmetic packaging format explained — compacts, palettes, tubes, bottles, jars, airless systems, and kits. Tooling costs, MOQs, and cost ranges.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Formats',
    readTime: '13 min read',
    image: '/images/portfolio/foil-stamped-cylinder.jpeg',
    gradient: 'linear-gradient(135deg,#1a1a2e,#16213e,#0f3460)',
    published: true,
  },
  {
    slug: 'luxury-beauty-packaging-guide',
    title: 'Luxury Beauty Packaging: What Separates Premium From Mass Market',
    description: 'What makes luxury beauty packaging feel premium — structural weight, closure engineering, finish layering, and sensory sequencing. The full breakdown.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Design',
    readTime: '14 min read',
    image: '/images/portfolio/velvet-interior-unboxing-kit.jpeg',
    gradient: 'linear-gradient(135deg,#0d2818,#1a4a2e,#2d6a4f)',
    published: true,
  },
  {
    slug: 'pcr-packaging-beauty-brands',
    title: 'PCR Packaging for Beauty Brands: What Post-Consumer Recycled Content Actually Means',
    description: 'PCR packaging uses post-consumer recycled plastic in beauty containers. What 30%, 50%, and 100% PCR means, what it costs, and how to verify claims.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Sustainability',
    readTime: '14 min read',
    image: '/images/portfolio/skincare-launch-pr-mailer.jpg',
    gradient: 'linear-gradient(135deg,#0f2027,#203a43,#2c5364)',
    published: true,
  },
  {
    slug: 'hdpe-vs-pet-packaging-comparison',
    title: 'HDPE vs PET Packaging: Which Plastic Is Right for Your Beauty Brand?',
    description: 'HDPE and PET compared on chemical resistance, clarity, weight, recyclability, PCR availability, and cost for beauty packaging.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Materials',
    readTime: '14 min read',
    image: '/images/portfolio/holiday-kits.jpeg',
    gradient: 'linear-gradient(135deg,#1a0a2e,#2e1a4a,#4a2c6a)',
    published: true,
  },
  {
    slug: 'soft-touch-lamination-packaging',
    title: 'Soft Touch Lamination for Packaging: When It Works and What It Costs',
    description: 'Soft touch lamination adds a velvet tactile surface to packaging at $0.08-$0.60 per unit. When it works, when it doesn\'t, and alternatives.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Finishes',
    readTime: '15 min read',
    image: '/images/portfolio/cosmetics-folding-carton.jpeg',
    gradient: 'linear-gradient(135deg,#2e1a0a,#4a2c1a,#6a3c2a)',
    published: true,
  },
  {
    slug: 'advent-calendar-packaging-beauty',
    title: 'Advent Calendar Packaging for Beauty Brands: What It Takes to Produce One',
    description: 'Custom advent calendar packaging costs $8-25+ per unit at 1,000-5,000 units and requires 6-8 months lead time. Structures, costs, and timeline.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Holiday',
    readTime: '14 min read',
    image: '/images/portfolio/24-door-advent-calendar.jpeg',
    gradient: 'linear-gradient(135deg,#0a2e1a,#1a4a3c,#2c6a5a)',
    published: true,
  },
  {
    slug: 'gift-set-packaging-design',
    title: 'Gift Set Packaging Design: Structures, Inserts, and Cost Decisions',
    description: 'Gift set packaging for beauty brands — rigid box, folding carton, and sleeve+tray structures. Insert types, cost drivers, and retailer requirements.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Holiday',
    readTime: '14 min read',
    image: '/images/portfolio/premium-beauty-gift-set1.jpg',
    gradient: 'linear-gradient(135deg,#1a0a2e,#3c1a5a,#5a2c7a)',
    published: true,
  },
  {
    slug: 'pr-kit-cost-breakdown',
    title: 'How Much Do Custom PR Kits Cost? A Tier-by-Tier Breakdown',
    description: 'Custom PR kit production costs $8-75+ per unit depending on tier. Basic mailers, branded kits, and premium experience builds with ROI framework.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Pricing',
    readTime: '13 min read',
    image: '/images/portfolio/soft-touch-spot-uv.jpg',
    gradient: 'linear-gradient(135deg,#2e0a1a,#4a1a2e,#6a2c3c)',
    published: true,
  },
  {
    slug: 'unboxing-experience-design-guide',
    title: 'Unboxing Experience Design: The Psychology of Packaging That Gets Filmed',
    description: 'Unboxing experience design for beauty brands — reveal moments, inserts, textures, packaging structure, costs, and retail fit.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Design',
    readTime: '16 min read',
    image: '/images/portfolio/holiday-epicutis-gift-sets.jpg',
    gradient: 'linear-gradient(135deg,#1a1a2e,#2e2e3e,#3c3c4e)',
    published: true,
  },
  {
    slug: 'eu-ppwr-packaging-requirements-beauty',
    title: 'EU PPWR Packaging Requirements for Beauty Brands: What to Change and When',
    description: 'EU PPWR packaging requirements affect any beauty brand selling into Europe. Recycled content targets, recyclability rules, and compliance timelines.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Compliance',
    readTime: '12 min read',
    image: '/images/portfolio/shelf-ready-display-unit.jpeg',
    gradient: 'linear-gradient(135deg,#0f2027,#1a3a43,#2c5a64)',
    published: true,
  },
  {
    slug: 'refillable-beauty-packaging-guide',
    title: 'Refillable Beauty Packaging: A Design Guide That Includes the Hard Parts',
    description: 'Refillable beauty packaging works when the system is designed for real consumer behavior. Refill types, engineering, cost modeling, and adoption data.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Sustainability',
    readTime: '16 min read',
    image: '/images/portfolio/influencer-adidas-nemesis.jpg',
    gradient: 'linear-gradient(135deg,#1a1a2e,#0f3460,#16213e)',
    published: true,
  },
  {
    slug: 'mono-material-packaging-design',
    title: 'Mono-Material Packaging Design for Beauty: The Technical Guide',
    description: 'Mono-material packaging design for beauty brands — recyclability, material choices, cost tradeoffs, compliance, and design limits.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Sustainability',
    readTime: '13 min read',
    image: '/images/portfolio/foil-stamped-cylinder.jpeg',
    gradient: 'linear-gradient(135deg,#1a1a2e,#16213e,#0f3460)',
    published: true,
  },
  {
    slug: 'custom-packaging-development-process',
    title: 'How Custom Packaging Development Works: From Brief to Shelf',
    description: 'The packaging development process from brief to shelf in 12-16 weeks. What happens at each stage, who is involved, and what decisions to make.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Planning',
    readTime: '15 min read',
    image: '/images/portfolio/velvet-interior-unboxing-kit.jpeg',
    gradient: 'linear-gradient(135deg,#0d2818,#1a4a2e,#2d6a4f)',
    published: true,
  },
  {
    slug: 'fragrance-packaging-design-guide',
    title: 'Fragrance Packaging Design: What Makes Perfume Packaging Premium',
    description: 'What makes fragrance packaging feel premium — box structure, board weight, finishes, costs, timelines, and common perfume packaging mistakes.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Design',
    readTime: '13 min read',
    image: '/images/portfolio/skincare-launch-pr-mailer.jpg',
    gradient: 'linear-gradient(135deg,#0f2027,#203a43,#2c5364)',
    published: true,
  },
  {
    slug: 'food-beverage-packaging-design-guide',
    title: 'Food and Beverage Packaging Design for Emerging Brands',
    description: 'Food and beverage packaging design — materials, compliance, shelf life, retail requirements, costs, and DTC-to-retail planning.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Design',
    readTime: '14 min read',
    image: '/images/portfolio/holiday-kits.jpeg',
    gradient: 'linear-gradient(135deg,#1a0a2e,#2e1a4a,#4a2c6a)',
    published: true,
  },
  {
    slug: 'custom-packaging-moq-guide',
    title: 'Custom Packaging MOQs: What Every Brand Needs to Know',
    description: 'Custom packaging MOQ ranges by format, why minimums exist, and how brands can lower order quantities without overbuying.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Planning',
    readTime: '11 min read',
    image: '/images/portfolio/cosmetics-folding-carton.jpeg',
    gradient: 'linear-gradient(135deg,#2e1a0a,#4a2c1a,#6a3c2a)',
    published: true,
  },
  {
    slug: 'custom-jewelry-packaging-cost',
    title: 'How Much Does Custom Jewelry Packaging Cost? A Real Pricing Guide',
    description: 'Custom jewelry packaging costs $3-$15 per unit for most branded boxes. Real cost drivers, MOQs, timelines, quote comparisons, and pricing strategy.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Pricing',
    readTime: '14 min read',
    image: '/images/portfolio/jewelry/olive-ave-ring-boxes.jpg',
    gradient: 'linear-gradient(135deg,#1a1a2e,#16213e,#0f3460)',
    published: true,
  },
  {
    slug: 'jewelry-packaging-design-guide',
    title: 'Jewelry Packaging Design Guide: Boxes, Inserts, Materials, and Unboxing',
    description: 'A complete jewelry packaging design guide covering ring boxes, necklace boxes, inserts, materials, finishes, unboxing, costs, MOQs, and approval steps.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Design',
    readTime: '13 min read',
    image: '/images/portfolio/jewelry/maor-jewelry-boxes.jpg',
    gradient: 'linear-gradient(135deg,#0d2818,#1a4a2e,#2d6a4f)',
    published: true,
  },
  {
    slug: 'jewelry-packaging-retail-vs-dtc',
    title: 'Jewelry Packaging for Retail vs. DTC: What Has to Change',
    description: 'Jewelry packaging for retail and DTC has different requirements. Structural, display, shipping, barcode, insert, and cost tradeoffs for brands.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Strategy',
    readTime: '13 min read',
    image: '/images/portfolio/jewelry/oak-park-jewelry-collection.jpg',
    gradient: 'linear-gradient(135deg,#0f2027,#203a43,#2c5364)',
    published: true,
  },
  {
    slug: 'luxury-jewelry-packaging-guide',
    title: 'Luxury Jewelry Packaging Guide: When Premium Packaging Is Worth It',
    description: 'Luxury jewelry packaging is worth it when presentation supports price, retail placement, gifting, and retention. Formats, costs, and tradeoffs.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Design',
    readTime: '14 min read',
    image: '/images/portfolio/jewelry/maor-collection.jpg',
    gradient: 'linear-gradient(135deg,#1a0a2e,#2e1a4a,#4a2c6a)',
    published: true,
  },
  {
    slug: 'packaging-cost-per-unit-benchmarks',
    title: 'Packaging Cost Per Unit Benchmarks by Product Category',
    description: 'Practical packaging cost per unit benchmarks: $1.50-$8.00 for beauty, $0.30-$3.00 for food, $3.00-$15.00 for jewelry. Real ranges by category.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Pricing',
    readTime: '11 min read',
    image: '/images/portfolio/foil-stamped-cylinder.jpeg',
    gradient: 'linear-gradient(135deg,#2e0a1a,#4a1a2e,#6a2c3c)',
    published: true,
  },
  {
    slug: 'sustainable-jewelry-packaging',
    title: 'Sustainable Jewelry Packaging: Materials, Costs, and Compliance',
    description: 'Sustainable jewelry packaging needs specific materials, claims, and compliance planning. FSC, recycled paper, molded fiber, mono-materials, and costs.',
    date: '2026-05-21',
    author: 'Jordan Harper',
    tag: 'Sustainability',
    readTime: '13 min read',
    image: '/images/portfolio/jewelry/made-by-mary-collection.jpg',
    gradient: 'linear-gradient(135deg,#0a2e1a,#1a4a3c,#2c6a5a)',
    published: true,
  },
]

export function getPublishedPosts(): BlogPost[] {
  return blogPosts.filter(p => p.published)
}

export function getAllPosts(): BlogPost[] {
  return blogPosts
}

export function getPostBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find(p => p.slug === slug)
}
