import type { Metadata } from 'next'
import PackagingCaseStudy from '@/components/PackagingCaseStudy'
import { buildCaseStudySchema } from '@/lib/case-study-schema'

const title = 'Artilect Packaging Reduction Case Study'
const description = 'How Artilect packaging was re-engineered to remove material and complexity while protecting the customer-facing experience.'
const image = '/images/work/artilect/custom-packaging.jpg'
export const metadata: Metadata = { title, description, alternates: { canonical: '/work/artilect-packaging-reduction' }, openGraph: { title: `${title} | Logic Pac`, description, type: 'article', images: [image] } }
export default function Page() {
  const schema = buildCaseStudySchema({ slug: 'artilect-packaging-reduction', headline: title, description, image, client: 'Artilect' })
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema.article) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema.breadcrumb) }} /><PackagingCaseStudy study={{
    client:'Artilect', eyebrow:'Packaging Reduction', title:'Remove the packaging the customer does not value.', lede:'A packaging-reduction program for Artilect focused on separating protection and presentation from material and complexity that no longer earned its place.', heroImage:image, heroAlt:'Artilect custom apparel packaging developed by Logic', meta:[['Client','Artilect'],['Category','Performance apparel'],['Focus','Material and cost reduction']], overviewTitle:'Cost reduction without making the brand feel cheaper.', overview:['Packaging cost programs often fail when they begin with a thinner material or a lower-cost supplier. Artilect required a more disciplined approach: understand what the package had to protect, what the customer actually saw, and which elements could be removed or redesigned.','The work was organized as a phased reduction program so protection, pack-out, and presentation could be evaluated before each change moved forward.'], constraints:[['Protect the product.','Reduction could not introduce damage, contamination, or inconsistent presentation.'],['Preserve the brand signal.','Customer-facing touchpoints still needed to feel intentional and appropriate for technical apparel.'],['Reduce hidden cost.','Material volume, assembly steps, storage, and freight all belonged in the cost model.'],['Create a workable transition.','Changes needed to move through sourcing and production without disrupting active programs.']], solutionTitle:'A phased packaging-reduction roadmap', solutions:[['Map every layer','Each packaging component was evaluated by job: protection, containment, identification, presentation, or convenience.'],['Separate value from habit','Legacy elements were challenged when they existed because of precedent rather than a current requirement.'],['Prototype the leaner system','Reduced configurations could be reviewed against actual product and handling needs before rollout.'],['Sequence the change','A phased roadmap made it possible to capture simpler wins while more structural changes were developed.']], outcomeTitle:'A leaner packaging direction grounded in function.', outcomes:['The Artilect work demonstrates how brands can reduce packaging by engineering out waste rather than stripping away the customer experience.','For beauty and wellness teams, the same method applies to oversized cartons, redundant inserts, decorative layers, and e-commerce packaging that has accumulated without a clear job.'], secondaryImage:'/images/work/artilect/seeding-kits.jpg', secondaryAlt:'Artilect seeding kits and packaging components', evidence:'Artilect is approved for public reference. Percentage savings and material-reduction figures are intentionally omitted here pending case-study-specific approval.', relatedHref:'/guides/material-decision-framework', relatedLabel:'Use the Material Decision Guide', projectType:'Packaging Cost Reduction'
  }} /></>
}
