import type { Metadata } from 'next'
import PackagingCaseStudy from '@/components/PackagingCaseStudy'
import { buildCaseStudySchema } from '@/lib/case-study-schema'

const title = 'Epicutis Packaging System Case Study'
const description = 'How a premium skincare packaging program expanded from a focused box brief into a coordinated system supporting 21+ SKUs and verified cost savings.'
const image = '/images/work/epicutis/epicutis-kits-group-grey.jpg'
export const metadata: Metadata = { title, description, alternates: { canonical: '/work/epicutis' }, openGraph: { title: `${title} | Logic Pac`, description, type: 'article', images: [image] } }

export default function Page() {
  const schema = buildCaseStudySchema({ slug: 'epicutis', headline: title, description, image, client: 'Epicutis' })
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema.article) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema.breadcrumb) }} /><PackagingCaseStudy study={{
    client: 'Epicutis', eyebrow: 'Beauty Packaging System', title: 'Packaging built to grow with a premium skincare brand.', lede: 'What began as a focused box brief expanded into primary packaging, secondary packaging, displays, inventory planning, and a coordinated system supporting a much larger SKU portfolio.', heroImage: image, heroAlt: 'Epicutis skincare kits and coordinated packaging produced by Logic',
    meta: [['Client','Epicutis'],['Category','Premium skincare'],['Scope','Multi-SKU packaging system']], overviewTitle: 'The brief grew because the brand grew.',
    overview: ['Epicutis needed packaging that protected a clinical, premium position while the product line expanded. A one-off box solution would not be enough once more products, displays, launches, and replenishment needs entered the system.','Logic developed packaging across primary and secondary formats and helped coordinate the sourcing and inventory layer behind it. For a brand team, that meant packaging decisions could stay consistent even as the number of SKUs and operational dependencies increased.'],
    constraints: [['Premium clinical positioning.','Every format had to feel precise and restrained rather than decorative for its own sake.'],['A growing SKU system.','New products and sets needed to belong to one visual and production family.'],['Availability at launch and replenishment.','Packaging had to be positioned before product, retail, and campaign dates created urgency.'],['Cost control without brand erosion.','Savings needed to come from sourcing, engineering, consolidation, and planning—not a visible downgrade.']],
    solutionTitle: 'A packaging program—not a collection of disconnected boxes', solutions: [['System consistency','Primary packs, cartons, kits, and displays were developed as parts of the same brand system.'],['Supplier coordination','Production was managed across the appropriate manufacturing partners with shared standards and clearer ownership.'],['Inventory planning','Packaging was planned and positioned to support launches and replenishment instead of relying on isolated emergency orders.'],['Continuous optimization','The program created room to improve material use, landed cost, and pack-out as volumes and formats evolved.']],
    outcomeTitle: 'A larger packaging footprint without losing control of the brand.', outcomes: ['The program supported Epicutis as its packaging footprint grew from three SKUs to more than 21. Verified internal materials also document 15% packaging cost savings.','For Logic Pac’s target buyer, the lesson is that packaging scale is not just a design challenge. It is a system of specifications, suppliers, approvals, inventory, and timing that needs one accountable owner.'], proof: [['3 → 21+','SKUs supported'],['15%','Verified packaging cost savings']], secondaryImage: '/images/work/epicutis/epicutis-gradient.jpg', secondaryAlt: 'Epicutis premium skincare packaging and products', evidence: 'The SKU growth and 15% cost-savings figures are the approved public Epicutis metrics. Broader operational outcomes belong to the Logic Agency engagement and are not attributed solely to Logic Pac.', relatedHref: '/guides/packaging-brief-template', relatedLabel: 'Use the Packaging Brief Template', projectType: 'Beauty Packaging Program'
  }} /></>
}
