import type { Metadata } from 'next'
import PackagingCaseStudy from '@/components/PackagingCaseStudy'
import { buildCaseStudySchema } from '@/lib/case-study-schema'

const title = 'Epicutis Packaging System Case Study'
const description = 'How a premium skincare packaging program expanded from a focused box brief into a coordinated system supporting 21+ SKUs and verified cost savings.'
const image = '/images/work/epicutis/epicutis-kits-group-grey.jpg'
export const metadata: Metadata = { title, description, alternates: { canonical: '/work/epicutis' }, openGraph: { title: `${title} | Logic Pac`, description, type: 'article', url: 'https://logic-pac.com/work/epicutis', images: [image] }, twitter: { card: 'summary_large_image', title: `${title} | Logic Pac`, description, images: [image] } }

export default function Page() {
  const schema = buildCaseStudySchema({ slug: 'epicutis', headline: title, description, image, client: 'Epicutis' })
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema.article) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema.breadcrumb) }} /><PackagingCaseStudy study={{
    client: 'Epicutis', eyebrow: 'Beauty Packaging System', title: 'From 3 SKUs to 21: how Epicutis scaled packaging without scaling headcount.', lede: 'Five years ago, Epicutis needed a box to hold two products. Today, Logic manages packaging, inventory, and procurement across 21+ SKUs — while the brand runs the same lean team it started with.', heroImage: image, heroAlt: 'Epicutis skincare kits and coordinated packaging produced by Logic',
    meta: [['Client','Epicutis'],['Category','Premium skincare'],['Scope','Multi-SKU packaging system']], overviewTitle: 'The brief grew because the brand grew.',
    overview: ['Epicutis started with a simple ask: make a box that holds these two things. That was five years and 18 SKUs ago. As the product line expanded from under 100,000 units to over a million annually, every new launch added packaging formats, supplier relationships, compliance requirements, and production timelines to a system that was never designed for that complexity.','Logic absorbed the operational weight so the Epicutis team did not have to hire for it. We took ownership of primary packaging, secondary packaging, retail displays, inventory planning, and supplier coordination — and built a managed inventory program so the brand could move on procurement without cash flow timing dictating the calendar. The result is a 7X growth trajectory managed through one partner, not five new hires.'],
    constraints: [['Premium clinical positioning.','Epicutis is a biotech-backed clinical skincare brand. Every format — from the primary pack to the retail display — had to communicate precision, not decoration.'],['7X SKU growth under one system.','New products, kits, and seasonal sets needed to fit one production and visual family, not get reinvented every launch.'],['Replenishment speed vs. ocean freight lead times.','Standard ocean freight cycles meant 30 to 60 days to restock. Campaign dates, retail windows, and co-manufacturer schedules could not wait that long.'],['Cost discipline without visible compromise.','Savings had to come from sourcing, engineering, and procurement planning — not thinner board stock or cheaper finishes that erode a $200+ price point.']],
    solutionTitle: 'A packaging program that runs like a supply chain — because it is one', solutions: [['Managed inventory from SLC.','Logic built a packaging inventory program out of our Salt Lake City warehouse. Epicutis can now replenish packaging in 7 days instead of waiting 30 to 60 days for the next ocean freight cycle.'],['Eliminated urgent airship costs.','By normalizing the procurement cycle and maintaining buffer stock, we removed the emergency air freight charges that had been treated as a cost of doing business.'],['Extended packaging credit.','Logic fronts packaging procurement so production timing is driven by the launch calendar, not cash flow cycles. That kind of capital commitment puts us in a different category than a packaging vendor.'],['Continuous engineering optimization.','As volumes grew from hundreds of thousands to over a million units, we re-engineered material specs, consolidated supplier relationships, and improved pack-out efficiency — delivering 15% verified cost savings without changing what the customer sees or touches.']],
    outcomeTitle: '7X growth, same team, one packaging partner.', outcomes: ['Epicutis went from 3 SKUs to 21+ and from under 100K units to over 1M annually. Their co-manufacturer saw reduced floor hold time and improved throughput because packaging was already staged and positioned. The brand’s lean operating team stayed lean — Logic absorbed the operational complexity that would have required multiple new hires across procurement, inventory, and supplier management.','The lesson for any scaling brand: packaging at volume is not a design problem. It is a procurement, inventory, cash flow, and coordination problem. The brands that solve it with one accountable partner — instead of a patchwork of vendors, freelancers, and emergency air shipments — protect their margins and their launch timelines at the same time.'], proof: [['3 → 21+','SKUs supported'],['15%','Verified cost savings'],['7 days','Replenishment cycle (from 30–60)']], secondaryImage: '/images/work/epicutis/epicutis-gradient.jpg', secondaryAlt: 'Epicutis premium skincare packaging and products', evidence: 'SKU growth from 3 to 21+, 15% verified cost savings, and 5-year relationship timeline are from approved Epicutis metrics. Operational outcomes including 7-day replenishment, airship cost elimination, and co-manufacturer throughput improvements are documented across the Logic Agency engagement.', relatedHref: '/guides/packaging-brief-template', relatedLabel: 'Use the Packaging Brief Template', projectType: 'Beauty Packaging Program'
  }} /></>
}
